#pragma config(Motor,  port2,           left13,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           left24,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           right13,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           right24,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"//Main competition background code...do not modify!
#include "driving.c"
void pre_auton()
{
  bStopTasksBetweenModes = true;
}
task autonomous()
{
	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}
task usercontrol()
{
	startTask(driving);
}
