#pragma config(Sensor, dgtl1,  pneumatics,     sensorDigitalOut)
#pragma config(Sensor, dgtl2,  ArmEnc,         sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  Right,          sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  Left,           sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  BRI,            sensorNone)
#pragma config(Sensor, I2C_2,  BLI,            sensorNone)
#pragma config(Sensor, I2C_3,  BRI,            sensorNone)
#pragma config(Sensor, I2C_4,  FRI,            sensorNone)
#pragma config(Motor,  port2,           L1R1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           FL,            tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           L2R2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           BL,            tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port6,           FR,            tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port8,           L3R3,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           BR,            tmotorVex393_MC29, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//https://www.vexforum.com/index.php/6146-robotc-programming-tips/p2#p53799
//1525
#define MOTOR_NUM               kNumbOfTotalMotors
#define MOTOR_MAX_VALUE         127
#define MOTOR_MIN_VALUE         (-127)
#define MOTOR_DEFAULT_SLEW_RATE 10      // Default will cause 375mS from full fwd to rev
#define MOTOR_FAST_SLEW_RATE    256     // essentially off
#define MOTOR_TASK_DELAY        15      // task 1/frequency in mS (about 66Hz)
#define MOTOR_DEADBAND          10
#pragma platform(VEX2)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "driving.c"
#include "auton.c"
void waitForPress(){//for auton selection
	while(nLCDButtons == 0){}
	wait1Msec(5);
}
void waitForRelease(){//for auton selection
	while(nLCDButtons != 0){}
	wait1Msec(5);
}
const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;
void pre_auton(){

}


task autonomous(){
	startTask(auton4);
}


task usercontrol(){
	startTask(driving);
}
