#pragma config(Sensor, dgtl1,  pneumatics,     sensorDigitalOut)
#pragma config(Motor,  port2,           L1L2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           FL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           L3,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           BL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           BR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           R3,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           R1R2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           FR,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

void pre_auton(){

}


task autonomous(){

}


task usercontrol(){
	while (true){

	}
}
