#pragma config(Sensor, in1,    pot1,           sensorPotentiometer)
#pragma config(Sensor, dgtl1,  pneumatics,     sensorDigitalOut)
#pragma config(Sensor, dgtl2,  LBEnc,          sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  RBEnc,          sensorQuadEncoder)
#pragma config(Motor,  port2,           L1R1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           FL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           L2R2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           BL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           BR,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           L3R3,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           FR,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//1525


#pragma platform(VEX2)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "driving.c"
#include "auton.c"
void pre_auton(){

}


task autonomous(){

}


task usercontrol(){
	startTask(driving);
}
